alias dkeyn='vim ~/home/env_docs/keybind/n.txt'
alias dkeyz='vim ~/home/env_docs/keybind/z.txt'
alias dkeyvn='vim ~/home/env_docs/keybind/vn.txt'
alias dkeyvf='vim ~/home/env_docs/keybind/vf.txt'
alias dkeyvt='vim ~/home/env_docs/keybind/vt.txt'
alias dkeyt='vim ~/home/env_docs/keybind/t.txt'
