# ----------------------------------------------------------------------------------------------------
# 雑多: 装飾、便利系など
# ----------------------------------------------------------------------------------------------------
# colorscheme
[[plugins]]
repo = 'https://github.com/w0ng/vim-hybrid'

[[plugins]]
repo = 'https://github.com/cocopon/iceberg.vim'

# neovim-remote
# terminalモードでvimを実行した際にvimをnestで起動せずに、カレントのvimでファイルを開けるようにするために必要
[[plugins]]
repo = 'https://github.com/mhinz/neovim-remote'

# vim-easymotion
# normalモードでの移動を楽にする
[[plugins]]
repo = 'https://github.com/Lokaltog/vim-easymotion'

# lightline
# ステータスラインのカスタマイズ用
[[plugins]]
repo = 'https://github.com/itchyny/lightline.vim.git'

# vim-signature
# マークを少し見やすくします
[[plugins]]
repo = 'https://github.com/kshenoy/vim-signature'

# vim-gitgutter
# git diffをマーカとして表示します
[[plugins]]
repo = 'https://github.com/airblade/vim-gitgutter'

# copilot
[[plugins]]
repo = 'https://github.com/github/copilot.vim'
# ----------------------------------------------------------------------------------------------------


# ----------------------------------------------------------------------------------------------------
# ファイラ
# ----------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'https://github.com/lambdalisue/fern.vim'

[[plugins]]
repo = 'https://github.com/lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'https://github.com/lambdalisue/fern-mapping-project-top.vim'
# ----------------------------------------------------------------------------------------------------


# ----------------------------------------------------------------------------------------------------
# lsp 関連
# ----------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'https://github.com/neovim/nvim-lspconfig'
rev = 'v0.1.7'

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
on_event = 'VimEnter'
hook_source = '''lua require('plugins.nvim-cmp')'''

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_source = 'nvim-cmp'

# null-ls.nvimの依存
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# フォーマッタ、リンタ用のプラグイン
[[plugins]]
repo = 'https://github.com/jose-elias-alvarez/null-ls.nvim'
on_source = 'plenary.nvim'
rev = '0.7-compat'

# LSP用のシグネチャ表示（関数の引数入力時の説明表示）
[[plugins]]
repo = 'ray-x/lsp_signature.nvim'

# LSP用のリッチなUI
# アウトライン表示、定義・参照の表示など
# ちょいちょいバグるのでバージョン固定する
[[plugins]]
repo = 'glepnir/lspsaga.nvim'
rev = 'b8f131f174c8cb7e1d5a3424c7290ec4b0ba7967'
# ----------------------------------------------------------------------------------------------------
