# colorscheme
[[plugins]]
repo = 'https://github.com/w0ng/vim-hybrid'

# colorscheme: hybridよりもおとなしい色合い(言い方を変えると色のメリハリが弱い
[[plugins]]
repo = 'https://github.com/cocopon/iceberg.vim'


# ファイラ
[[plugins]]
repo = 'https://github.com/lambdalisue/fern.vim'

[[plugins]]
repo = 'https://github.com/lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'https://github.com/lambdalisue/fern-mapping-project-top.vim'


[[plugins]]
repo = 'https://github.com/mhinz/neovim-remote'
# terminalモードでvimを実行できるようにするために必要

[[plugins]]
repo ='https://github.com/rking/ag.vim'


# ctrlp is plugin is finder, but fzf is better than this
# [[plugins]]
# repo = 'https://github.com/ctrlpvim/ctrlp.vim.git'

# vim-signature is plugin to extend mark
[[plugins]]
repo = 'https://github.com/kshenoy/vim-signature'

# vim-easymotion is plugin to extend motion
[[plugins]]
repo = 'https://github.com/Lokaltog/vim-easymotion'

# vim-surround is plugin to surround parentheses, brackets, quotes
# disable this plugin, because of I don't use this plugin recently.
# [[plugins]]
# repo = 'https://github.com/tpope/vim-surround.git'

# tComment is plugin for comment out
# disable this plugin, because of I don't use this plugin recently.
# [[plugins]]
# repo = 'https://github.com/vim-scripts/tComment'

# syntastic is plugin for syntax check
[[plugins]]
repo = 'https://github.com/scrooloose/syntastic.git'

# tagbar is plugin to display tag list in side bar
# this plugin require ctags
[[plugins]]
repo = 'https://github.com/majutsushi/tagbar.git'

# for viewing markdown on tagbar
[[plugins]]
repo = 'https://github.com/jszakmeister/markdown2ctags.git'


# SrcExpl is plugin to display definitions and declarations
# this plugin require ctags
[[plugins]]
repo = 'https://github.com/wesleyche/SrcExpl'

# lightline is plugin to configure statusline/tabline
[[plugins]]
repo = 'https://github.com/itchyny/lightline.vim.git'

# formater for js, tsx, md, and others
[[plugins]]
repo = 'https://github.com/prettier/vim-prettier.git'

# git
# basic plugin
[[plugins]]
repo = 'https://github.com/tpope/vim-fugitive'

# git log viewer
[[plugins]]
repo = 'https://github.com/cohama/agit.vim'

# show git diff marker
[[plugins]]
repo = 'https://github.com/airblade/vim-gitgutter'

# cscope
[[plugins]]
repo = 'https://github.com/ronakg/quickr-cscope.vim'


# LSP
# [[plugins]]
# repo = 'https://github.com/prabirshrestha/vim-lsp'
# 
# [[plugins]]
# repo = 'https://github.com/prabirshrestha/asyncomplete.vim'
# 
# [[plugins]]
# repo = 'https://github.com/prabirshrestha/asyncomplete-lsp.vim'




[[plugins]]
repo = 'https://github.com/neovim/nvim-lspconfig'

# [[plugins]]
# repo = 'hrsh7th/nvim-cmp'
# on_event = 'VimEnter'
# hook_source = '''lua require('plugins.nvim-cmp')'''
# 
# [[plugins]]
# repo = 'hrsh7th/cmp-buffer'
# on_source = 'nvim-cmp'
# 
# [[plugins]]
# repo = 'hrsh7th/cmp-path'
# on_source = 'nvim-cmp'
# 
# [[plugins]]
# repo = 'hrsh7th/cmp-nvim-lsp'
# on_source = 'nvim-cmp'
# 
# [[plugins]]
# repo = 'L3MON4D3/LuaSnip'
# on_source = 'nvim-cmp'

# [[plugins]]
# repo = 'https://github.com/hrsh7th/cmp-cmdline'
# [[plugins]]
# repo = 'https://github.com/hrsh7th/cmp-vsnip'
# [[plugins]]
# repo = 'https://github.com/hrsh7th/vim-vsnip'

