# ----------------------------------------------------------------------------------------------------
# 雑多: 装飾、便利系など
# ----------------------------------------------------------------------------------------------------
# colorscheme
[[plugins]]
repo = 'https://github.com/w0ng/vim-hybrid'

# neovim-remoteは、terminalモードでvimを実行した際にvimをnestで起動せずに、カレントのvimでファイルを開けるようにするために必要
[[plugins]]
repo = 'https://github.com/mhinz/neovim-remote'

# vim-signature: マークを少し見やすくします
[[plugins]]
repo = 'https://github.com/kshenoy/vim-signature'

# vim-easymotion: normalモードでの移動を楽にする
[[plugins]]
repo = 'https://github.com/Lokaltog/vim-easymotion'

# lightline: ステータスラインのカスタマイズ用
[[plugins]]
repo = 'https://github.com/itchyny/lightline.vim.git'
# ----------------------------------------------------------------------------------------------------


# ----------------------------------------------------------------------------------------------------
# ファイラ
# ----------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'https://github.com/lambdalisue/fern.vim'

[[plugins]]
repo = 'https://github.com/lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'https://github.com/lambdalisue/fern-mapping-project-top.vim'
# ----------------------------------------------------------------------------------------------------


# ----------------------------------------------------------------------------------------------------
# git 関連
# ----------------------------------------------------------------------------------------------------
# basic plugin
[[plugins]]
repo = 'https://github.com/tpope/vim-fugitive'

# git log viewer
[[plugins]]
repo = 'https://github.com/cohama/agit.vim'

# show git diff marker
[[plugins]]
repo = 'https://github.com/airblade/vim-gitgutter'
# ----------------------------------------------------------------------------------------------------


# ----------------------------------------------------------------------------------------------------
# lsp 関連
# ----------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'https://github.com/neovim/nvim-lspconfig'

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
on_event = 'VimEnter'
hook_source = '''lua require('plugins.nvim-cmp')'''

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_source = 'nvim-cmp'

# null-ls.nvimの依存
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# フォーマッタ、リンタ用のプラグイン
[[plugins]]
repo = 'https://github.com/jose-elias-alvarez/null-ls.nvim'
on_source = 'plenary.nvim'

# j-hui/fidget.nvim: LSのステータス表示
[[plugins]]
repo = 'j-hui/fidget.nvim'

# LSP用のシグネチャ表示（関数の引数入力時の説明表示）
[[plugins]]
repo = 'ray-x/lsp_signature.nvim'

# LSP用のリッチなUI
# outline
[[plugins]]
repo = 'glepnir/lspsaga.nvim'
# ----------------------------------------------------------------------------------------------------
