#!/bin/bash

export TMUX_VERSION=${TMUX_VERSION:-3.3}

# CentOS7, Rocky8 require <=0.7.2
# NVIM-0.8.X は、GLIBC_2.29を要求してくるがRocky8のGLIBは2.28なので、0.7.2を利用します
export NEOVIM_VERSION=${NEOVIM_VERSION:-v0.7.2}

# CentOS7 require <=16.20.0
export NODE_VERSION=${NODE_VERSION:-16.20.0}

export GO_VERSION=${GO_VERSION:-1.22.5}

export SETUP_RUST=${SETUP_RUST:-false}
