#!/bin/bash

export HOME_ROOT_DIR=${HOME}/home

export TMUX_VERSION=${TMUX_VERSION:-3.4}

export NEOVIM_VERSION=${NEOVIM_VERSION:-v0.10.4}

export NODE_VERSION=${NODE_VERSION:-22.19.0}

# Go releases: https://go.dev/dl/
export GO_VERSION=${GO_VERSION:-1.25.7}

export FZF_VERSION=${FZF_VERSION:-0.56.3}

export SHFMT_VERSION=${SHFMT_VERSION:-3.5.1}
export NVM_VERSION=${NVM_VERSION:-0.40.3}

# Rust tools settings
export ENABLE_RUST=${ENABLE_RUST:-false}
export ENABLE_MARKDOWN_OXIDE=${ENABLE_MARKDOWN_OXIDE:-false}
export CARGO_BINSTALL_VERSION=${CARGO_BINSTALL_VERSION:-1.15.10}
export MARKDOWN_OXIDE_VERSION=${MARKDOWN_OXIDE_VERSION:-0.25.9}
export WATCHEXEC_VERSION=${WATCHEXEC_VERSION:-1.21.1}

if [ -f ~/home_ex/xdgconfig/confrc ]; then
    . ~/home_ex/xdgconfig/confrc
fi
